### ISSUE TITLE
error: argument --fw: invalid choice: '1001' (choose from '900', '1100')

### ISSUE THREAD

**Issue by majed207** [PSGO/PPPwnGo#1]
i try to use fw 10.01 and every time it fails idk why i have used 3 ethernet cables and it did noting pls help or fix

**Comment by PSGO** [comment]
now
Supported versions are:

FW 9.00
FW 9.03 / 9.04
FW 9.50 / 9.60
FW 10.00 / 10.01
FW 10.50 / 10.70 / 10.71
FW 11.00
more can be added (PRs are welcome)
