### ISSUE TITLE
Stuck at sending stage2 payload

### ISSUE THREAD

**Issue by IRONB0SS** [PSGO/PPPwnGo#10]
![IMG_20240510_004107_813.jpg](https://github.com/PSGO/PPPwnGo/assets/97769328/39b506db-cbcc-4998-bac9-9bfd47223dd8)

Latest python, installed everything in python folder, turned off firewall and anti virus

What I'm missing?

Edit : my other PC is good but this laptop has problem

**Comment by Najeraq** [comment]
same happens to me, it may be a problem of missing or corrupted requirements based on that your other pc did work, i cant figure what the problem might be thought.

**Comment by IRONB0SS** [comment]
> same happens to me, it may be a problem of missing or corrupted requirements based on that your other pc did work, i cant figure what the problem might be thought.

I reinstalled everything and still no dice
