### ISSUE TITLE
Stuck on line:  [*] Waiting for LCP configure request...

### ISSUE THREAD

**Issue by MrEd8** [PSGO/PPPwnGo#11]
- STAGE 1 always gets stuck recording in this phase "[*] Waiting for LCP configure request..." .
- Setup: win10, PS4 11.00
- I tried connecting directly to the network and also via D-link and the behavior is the same. More than 50x attempts
- when trying a different PPPwn GUI 1.5 - error occurred - Pinning to CPU 0...93%

**Comment by PSGO** [comment]
下载最新版

**Comment by chronoss09** [comment]
> * STAGE 1 always gets stuck recording in this phase "[*] Waiting for LCP configure request..." .
> * Setup: win10, PS4 11.00
> * I tried connecting directly to the network and also via D-link and the behavior is the same. More than 50x attempts
> * when trying a different PPPwn GUI 1.5 - error occurred - Pinning to CPU 0...93%

You are on Slim console ?
