### ISSUE TITLE
STAGE 2: ERROR

### ISSUE THREAD

**Issue by elegido22** [PSGO/PPPwnGo#13]
Just when stage 2 start, it seem that it have trouble to defeat the KASLR.

![image](https://github.com/PSGO/PPPwnGo/assets/84634461/412a7b6b-6584-4215-a2ad-20005a66fe21)

**Comment by Hit15** [comment]
same problm...use linux

**Comment by lomismous** [comment]
test firmware ???? 11.00 u 9.00 ????

**Comment by elegido22** [comment]
11 here, finally after 9383738384747437 try’s and 2828373737373 reboots it’s continues. I see that it’s depend of memory fail it gets on stage 1.

**Comment by PSGO** [comment]
Use the latest version
