### ISSUE TITLE
Windows defender

### ISSUE THREAD

**Issue by FoxygamerYT2557** [PSGO/PPPwnGo#18]
i try to download the file but windows defender block it and i already scan the file in totalvirus and there is too much problems and i need help 
![imagen_2024-05-14_080308201](https://github.com/PSGO/PPPwnGo/assets/169816726/08d68b11-37fb-4269-ac80-df23adc226ce)

**Comment by chronoss09** [comment]
i have the same problem, juste ignore it and recover the file !!!
