### ISSUE TITLE
goldhen donst load on 9.03

### ISSUE THREAD

**Issue by Conan179** [PSGO/PPPwnGo#19]
Hi first.
I have a PS4 with 9.03 and I can't get it to start.
The hack itself should work, the application says done at the bottom, the TV says Pwned at the top left.
But no gold is loaded, the stick is definitely exfat, I formatted the stick with Windows, Linux (on a Steamdeck) and on the PS4.
I have them on the stick as “payload.bin” and “goldhen.bin”.
Can someone help me?

**Comment by lomismous** [comment]
only 9.00 and 11.00  goldhen --- payload

**Comment by lomismous** [comment]
Add GoldHEN2.4b17.2 for 11.00/10.01/10.00/9.00 Thanks@SiSTRo！！！
