### ISSUE TITLE
stage 1 memory corruption scanning for corrupted object failed fw 10.01

### ISSUE THREAD

**Issue by majed207** [PSGO/PPPwnGo#2]
it failed 6 times and i dont know why pls help

**Comment by andewq121** [comment]
too 
10.50 
corrupted object failed 100%
failed

**Comment by majed207** [comment]
> too 10.50 corrupted object failed 100% failed

what do you mean

**Comment by andewq121** [comment]
i have this error too
try change version on 1070
i get next stage but my console reboot

**Comment by majed207** [comment]
> too 10.50 corrupted object failed 100% failed
well it worked after restarting my  ps4 but it crashed at te end

**Comment by PSGO** [comment]
> too 10.50 corrupted object failed 100% failed

redownload the new version

**Comment by DarkLuis1997** [comment]
once it hits [+] STAGE 2: KASLR defeat
[*] Defeating KASLR... my ps4 go into boot mode and then i try it 3 times restarted pc and pc and still the same it only happens when its at stage 2 Please help Right Away or anybody.

**Comment by PSGO** [comment]
> redownload the new version

redownload the new version， try again

**Comment by PSGO** [comment]
If it is stuck, fails, crashes or loses power, repeat 4&5，if it fails more than 3 times in a row, please restart PS4 and PC.

**Comment by majed207** [comment]
> If it is stuck, fails, crashes or loses power, repeat 4&5，if it fails more than 3 times in a row, please restart PS4 and PC.
it crashes after it os done idk why but it happens every time it passes stage 2
