### ISSUE TITLE
reset in 9.03 

### ISSUE THREAD

**Issue by lomismous** [PSGO/PPPwnGo#4]
the pppwnGo 
once it is executed in the second step!!!
kernel panic everything turns off  please fix this on ps4 9.03

**Comment by lomismous** [comment]
in linux ubuntu 18 it works perfect!!! PPPwn in PS4 firmware 9.03 the PPPwn in box clearly appears in less than 120 seconds

**Comment by lomismous** [comment]
In the case of Windows 7 I installed everything correctly but PPPwnGo has problems working!!! In my case I am testing firmware 9.03 on PS4 and it always goes into kernel panic and the console turns off!!!

**Comment by lomismous** [comment]
Python, pip, scapy, npcap 1.79 was installed correctly and yet it still has execution errors!!! in PS4 firmware 9.03 they must correct the code in Python to improve execution

**Comment by lomismous** [comment]
![error](https://github.com/PSGO/PPPwnGo/assets/168940755/528ccc3b-6164-464b-8bb8-84aa62585949)

version 1.5 is paralyzed and does not advance

**Comment by PSGO** [comment]
The success rate is related to the environment，upgrade to the latest version of Python, or try replacing 9.03 stage1. bin&stage2. bin
