### ISSUE TITLE
"Sending stage2 payload..." stuck.

### ISSUE THREAD

**Issue by Huguitis** [PSGO/PPPwnGo#6]
"Sending stage2 payload..." stuck for like 5 minutes. Then it shows "Done!" but no notification and no Debug Settings in PS4. 

Stuck for 5 minutes:
![image](https://github.com/PSGO/PPPwnGo/assets/65133800/42cc5a5f-e567-4876-876f-9b7025161137)

**Comment by PSGO** [comment]
版本多少？使用最新版，多试几次

**Comment by Huguitis** [comment]
> 版本多少？使用最新版，多试几次

- Using latest program version.
- Using PS4 11.00 version.
- I've already tried it about 30 times and all failed.

**Comment by PSGO** [comment]
> > 版本多少？使用最新版，多试几次
> 
> * Using latest program version.
> * Using PS4 11.00 version.
> * I've already tried it about 30 times and all failed.

这很奇怪  我让朋友的11.00试了一下   是正常的  会出现debug menu

**Comment by PSGO** [comment]
更新一下python

**Comment by Huguitis** [comment]
> 更新一下python

I'm using latest stable Python version (3.12.3)

**Comment by PSGO** [comment]
重新下载新版pppwngo
