### ISSUE TITLE
Can we implement support for the use of the openwrt plugin

### ISSUE THREAD

**Issue by ytalm** [PSGO/PPPwnGo#7]
在软路由上可以作为实现支持openwrt插件使用吗

**Comment by PSGO** [comment]
建议现阶段先手动输入命令，除了执行慢，稳定性还不错

**Comment by ytalm** [comment]
> 建议现阶段先手动输入命令，除了执行慢，稳定性还不错

如果能支持openwrt路由作为插件使用，可以不用每次使用PS都打开电脑
