### ISSUE TITLE
error scan corrupted object

### ISSUE THREAD

**Issue by andewq121** [PSGO/PPPwnGo#9]
![image](https://github.com/PSGO/PPPwnGo/assets/168224103/d4b22865-6668-4f70-9608-b3f77cbc98c7)

11.00

**Comment by Huguitis** [comment]
Retry

**Comment by andewq121** [comment]
i did it near 10 attempts and all error

**Comment by AymericKing** [comment]
same

**Comment by PSGO** [comment]
下载最新版  使用C++
